name: Continuous Deployment to Openshift
on:
  push:
    branches:
      - master
jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install CLI tools from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.13"

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OKD4_HOST }}
          openshift_token: ${{ secrets.OKD4_TOKEN }}
          certificate_authority_data: ${{ secrets.OKD4_CA }}
          namespace: 'verseghy-website-beta'

      - name: Buildah Build
        uses: redhat-actions/buildah-build@v2
        with:
          image: verseghy/website_frontend2
          tags: latest
          containerfiles: |
            ./Dockerfile

      - name: Push To Dockerhub
        uses: redhat-actions/push-to-registry@v2
        with:
          image: verseghy/website_frontend2
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_AT }}

      - name: Restart deployment
        shell: bash
        run: |
          oc rollout restart deployment website-frontend2
